### ISSUE TITLE
Run as Part of Mix Format

### ISSUE THREAD

**Issue by lukashambsch** [surface-ui/surface_formatter#28]
Is there any way to configure this to run as part of the `mix format` command?

**Comment by paulstatezny** [comment]
Hi @lukashambsch ! Thanks for chiming in.

As far as I understand @msaraiva has spoken with José Valim about this, and it sounds like there are plans to expand `mix format` be extensible, so that Surface could hook into it to format the Surface sigils.

Unfortunately, we're not there yet, and these things take time. 😄 But yes, whenever `mix format` adds support, the Surface team intends to hook into it so that you don't need to run `mix surface.format` separately.

I'm going to close this since there's no current path forward, but feel free to comment back! Thanks!

**Comment by msaraiva** [comment]
I'm not sure but maybe it would be possible to achieve something similar using aliases? https://hexdocs.pm/mix/1.12/Mix.html#module-aliases

**Comment by lukashambsch** [comment]
Thanks for the responses! Exciting to hear that it may be possible in the future. I'll look into aliases in the meantime.
