### ISSUE TITLE
Integrate to mix format plugin

### ISSUE THREAD

**Issue by wingyplus** [surface-ui/surface_formatter#46]
The issue would be in the future but I've a library that integrate surface_formatter to [mix format plugin](https://github.com/elixir-lang/elixir/pull/11246) at this [repository](https://github.com/wingyplus/surface_formatter_plugin/blob/main/test/surface_formatter_plugin_test.exs). It would be great if it can merge into surface_formatter repo in the future. ^^

**Comment by wingyplus** [comment]
FYI: I created a mix format hook [here](https://hex.pm/packages/surface_formatter_plugin).

**Comment by paulstatezny** [comment]
Hi @wingyplus, thanks for creating an issue to communicate about this!

The long/medium term plan is that `surface_formatter` is likely going to be absorbed into the Surface library itself once Elixir 1.13 is released. We are aware of this coming change to Elixir, and in fact the feature was added at least in part due to Marlus Saraiva's discussions with José Valim about Surface's desire to hook into `mix format`. 😄

I'm going to go ahead and close this, since it's on our radar and will be available immediately or very soon after Elixir 1.13 is released. Thanks again!
